version: "3"

services:
  database:
    image: "postgres:16-alpine"
    container_name: deutsche-bahn-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=deutsche_bahn_data
      - POSTGRES_INITDB_ARGS=--locale=en_US.utf8 --encoding=UTF8
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    networks:
      postgres-network:
        aliases:
          - database
    volumes:
      - $HOME/deutsche-bahn-data/db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      args:
        - API_BASE_URL=$BASE_URL/api
    container_name: deutsche-bahn-app
    environment:
      - DATA_DIR=/app/data/
      - XML_DIR=/app/data/xml/
      - EVA_DIR=/app/data/eva/
      - DB_HOST=database
      - POSTGRES_DB=deutsche_bahn_data
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - API_KEY=$API_KEY
      - CLIENT_ID=$CLIENT_ID
      - PRIVATE_API_KEY=$PRIVATE_API_KEY
      - BASE_URL=$BASE_URL
      - PRODUCTION=$PRODUCTION
    ports:
      - "5000:5000"
    volumes:
      - $HOME/deutsche-bahn-data/xml/:/app/data/xml/
      - $HOME/deutsche-bahn-data/eva/:/app/data/eva/
    networks:
      postgres-network:
        aliases:
          - app
    depends_on:
      database:
        condition: service_healthy

networks:
  postgres-network:
    name: deutsche-bahn-postgres-network
    driver: bridge
