version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=deutsche_bahn_data
    networks:
      - postgres-network
    volumes:
      - $HOME/deutsche-bahn-data/db-data/:/var/lib/postgresql/data/

networks:
  postgres-network:
    driver: bridge
